### ISSUE TITLE
String to Key

### ISSUE THREAD

**Issue by dbrgn** [pyfisch/keyboard-types#3]
There's no function to get a `Key` from a `&str`, right? Do you plan to add such a function?

It could probably easily be generated by using `convert.py` and linear search, falling back to `Key::Character` if none of the other keys matches.

**Comment by pyfisch** [comment]
No there is currently no function to get a `Key` from a `&str` mainly it is not needed for the Servo browser. Servo  only converts typed `Key`s to strings but not the other way around.

As you say it would be easy to add by modifying `convert.py`. Do you have a project that needs this function? I would be glad to add it.

Notes:

* use [binary_search_by](https://doc.rust-lang.org/std/primitive.slice.html#method.binary_search_by) instead of linear search
* also implement it for `Code`
* Only fall back to character if it is a single character + zero or more combining marks

**Comment by pyfisch** [comment]
Closed by #4
