### ISSUE TITLE
Release v0.7

### ISSUE THREAD

**Issue by pyfisch** [pyfisch/keyboard-types#35]
There is a number of commits since the last release <https://github.com/pyfisch/keyboard-types/compare/v0.6.2...main>, mainly modernizing the code and CI to conform to best practices.

@waywardmonkeys Thank you for updating the repository. Do you want to make more changes before the next release?

@madsmtm In #19 you outline the needs of winit. What are the current plans for integrating this crate into winit and which changes should be in the next release?

**Comment by waywardmonkeys** [comment]
I think the update to 2021 edition …  I think everything I wanted for glazier is in now.

**Comment by waywardmonkeys** [comment]
I will ask in the linebender group if they have anything else

**Comment by DJMcNab** [comment]
In future, I (for [glazier](https://github.com/linebender/glazier/)) would like to avoid allocating for our `KeyEvent` handling.
That is not trivial with `Key::Character` being a `String` (rather than, say, a `Cow<'a, str>`).

However, the exact shape of this isn't clear, and has already been discussed quite heavily elsewhere. It also doesn't block us, it's entirely a nice-to-have, so isn't a consideration for v0.7. Additionally, I've not measured the performance/memory impact, which is likely negligible.

We are also aware that it is possible to just reuse the same `String` in most cases cases, by only passing a `&` reference, so we may end up just using that strategy

**Comment by pyfisch** [comment]
Done #39.
